DROP TABLE IF EXISTS t_category;
CREATE TABLE IF NOT EXISTS t_category(
  fid INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  fname VARCHAR(20) NOT NULL DEFAULT '' COMMENT '用户名',
  fadded_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
  fupdate_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  fenable VARCHAR(1) NOT NULL DEFAULT 'Y',
  PRIMARY KEY(fid)
)ENGINE=INNODB DEFAULT CHARSET=utf8mb4;