DROP TABLE IF EXISTS t_notifications;
CREATE TABLE IF NOT EXISTS t_notifications (
  fid INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	ftype VARCHAR(255) NOT NULL DEFAULT '' COMMENT '通知类型',
	forigin VARCHAR(50) NOT NULL DEFAULT 'system' COMMENT '通知来源(system/用户名)',
	fto VARCHAR(50) NOT NULL DEFAULT '' COMMENT '通知目标(用户名)',
	fcontent VARCHAR(1000) NOT NULL DEFAULT '' COMMENT '通知内容',
	fadded_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
	fupdate_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	fenable VARCHAR(1) NOT NULL DEFAULT 'Y',
	PRIMARY KEY(`fid`)
)ENGINE=INNODB DEFAULT CHARSET=utf8mb4;