DROP TABLE IF EXISTS t_usercoltags;
CREATE TABLE IF NOT EXISTS t_usercoltags(
  fid INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  fuser VARCHAR(255) NOT NULL DEFAULT '' COMMENT '用户名',
  ftag VARCHAR(100) NOT NULL DEFAULT '默认' COMMENT '标签',
  fadded_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
  fupdate_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  fpost_id INT(11) NOT NULL DEFAULT 0 COMMENT '链接ID',
  fshare VARCHAR(1) NOT NULL DEFAULT 'Y',
  fenable VARCHAR(1) NOT NULL DEFAULT 'Y',
  PRIMARY KEY(fid)
)ENGINE=INNODB, CHARSET=utf8mb4;